name: linter-frontend
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "${{ github.workspace }}/frontend"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"
      - name: npm install
        run: "npm install"
      - name: npm run lint
        run: "npm run lint"