version: "3"

services:
  mysql:
    image: mysql:latest
    env_file: .env
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: ${TZ}
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  nginx:
    image: nginx:1.21-alpine
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx/conf/proxy.conf:/etc/nginx/conf.d/default.conf
  app:
    image: node:14.16.0-buster
    environment:
      - MYSQL_SERVER=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TZ}
      - CHOKIDAR_USEPOLLING=true

    #コンテナを起動させ続けるよう設定
    tty: true
    ports:
      - '3000:3000'

    # ソースコードを格納するフォルダをマウント
    #（ホスト側の./apiをコンテナの/appにマウント）
    volumes:
      - ./app:/app

    # 起動時のカレントフォルダを指定
    working_dir: /app/src/db

    # 起動後に実行するコマンドを指定
    command: >
      bash -c "npm install &&
      node app.js"

    #依存関係（apiコンテナより先にdbコンテナが起動するように設定）
    depends_on:
      - mysql